// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC92UueFaYmGG1OSqZ_aSwITfXkOV9Ofco',
    appId: '1:638849172136:android:9e5c227825149af933789d',
    messagingSenderId: '638849172136',
    projectId: 'note-app-6bdf2',
    storageBucket: 'note-app-6bdf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7Guv2PKv2Fs3AxG9BEdKSLVqfmBj3elc',
    appId: '1:638849172136:ios:cea98efcb8824c3b33789d',
    messagingSenderId: '638849172136',
    projectId: 'note-app-6bdf2',
    storageBucket: 'note-app-6bdf2.appspot.com',
    iosClientId:
        '638849172136-h4g2a9hpe0rhqehjmd9q0sld8mtvumlp.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );
}
